### ISSUE TITLE
Document/fix creating an instance with `Default Project`

### ISSUE THREAD

**Issue by Manouchehri** [aimoda/terraform-provider-corellium#74]
Basically, I want this to work:

```hcl
terraform {
  required_providers {
    corellium = {
      source = "aimoda/corellium"
      version = "~> 1.0.0"
    }
  }
}

provider "corellium" {
  token = "removed.removed"
  host = "app.corellium.com"
}

resource "corellium_v1instance" "student_instance" {
  name = "test"
  flavor = "iphone7plus"
  os = "15.7.6"
}
```

`project`

**Comment by henrybarreto** [comment]
I confirmed that the configuration you wanted works with the PR linked, but using the enterprise instance. I don't know if it could be a problem.

**Comment by Manouchehri** [comment]
I'm going to wait to merge this in until Monday, as I don't want to change anything until DEFCON is over on Monday. =)
